@extends('layouts.base')

@section('page-title', 'Glossary – Marathon Digital Holdings')

@section('page-class', 'page-template-default page page-id-389 fl-theme-builder-header fl-theme-builder-header-header fl-theme-builder-footer fl-theme-builder-footer-footer fl-theme-builder-singular fl-theme-builder-singular-page fl-framework-base fl-preset-default fl-full-width fl-search-active has-blocks fl-builder-breakpoint-large')

@section('page-content')

    <div class="uabb-js-breakpoint" style="display: none;"></div>

    @include('pages.includes.header')


    <div id="fl-main-content" class="fl-page-content" itemprop="mainContentOfPage" role="main">

        <div class="fl-builder-content fl-builder-content-95 fl-builder-global-templates-locked" data-post-id="95">
            <div class="fl-row fl-row-full-width fl-row-bg-photo fl-node-603e7e6d8abef fl-row-bg-overlay" data-node="603e7e6d8abef">
                <div class="fl-row-content-wrap">
                    <div class="fl-row-content fl-row-fixed-width fl-node-content">

                        <div class="fl-col-group fl-node-603e7e6d85253" data-node="603e7e6d85253">
                            <div class="fl-col fl-node-603e7e6d8525a" data-node="603e7e6d8525a">
                                <div class="fl-col-content fl-node-content">
                                    <div class="fl-module fl-module-heading fl-node-603e7e6d8525b" data-node="603e7e6d8525b">
                                        <div class="fl-module-content fl-node-content">
                                            <h1 class="fl-heading">
                                                <span class="fl-heading-text">Glossary</span>
                                            </h1>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="page-content-area" class="fl-row fl-row-full-width fl-row-bg-color fl-node-603e201c025b7" data-node="603e201c025b7">
                <div class="fl-row-content-wrap">
                    <div class="fl-row-content fl-row-fixed-width fl-node-content">

                        <div class="fl-col-group fl-node-603e201c025bc" data-node="603e201c025bc">
                            <div class="fl-col fl-node-603e201c025c5" data-node="603e201c025c5">
                                <div class="fl-col-content fl-node-content">
                                    <div class="fl-module fl-module-fl-post-content fl-node-603e201c025c6" data-node="603e201c025c6">
                                        <div class="fl-module-content fl-node-content">

                                            <h2>Bitcoin (BTC)</h2>


                                            <p>A type of digital currency in which a record of transactions is maintained and new units of currency are generated by the computational solution of mathematical problems, and which operates independently of a central bank; a unit of bitcoin.</p>


                                            <h2>Blockchain</h2>


                                            <p>A system in which a record of transactions made in bitcoin or another cryptocurrency are maintained across several computers that are linked in a peer-to-peer network.</p>


                                            <h2>Block</h2>


                                            <p>A file that contains a “permanent” record of transactions.</p>


                                            <h2>Mining</h2>


                                            <p>The processing of transactions in the digital currency system, in which the records of current Bitcoin transactions, known as a
                                                <em>blocks</em>, are added to the record of past transactions, known as the blockchain.
                                            </p>


                                            <h2>Hash Rate</h2>


                                            <p>The Measure of a Miners Performance – the number of calculations a miner can perform in 1 second as it works to find a solution for a block.</p>


                                            <h2>Block Reward</h2>


                                            <p>The amount of BTC “awarded/earned” for successfully mining/verifying a block.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="uabb-js-breakpoint" style="display: none;"></div>
    </div>


    @include('pages.includes.footer')

@endsection
